### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/run/containers/registries.conf'

### ISSUE THREAD

**Issue by miabbott** [projectatomic/registries#23]
On the Fedora Atomic Host Continuous stream[0], the `registries` service is failing to start:

```
# systemctl status registries
● registries.service - SystemWide Container Registries
   Loaded: loaded (/usr/lib/systemd/system/registries.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2017-09-15 17:13:47 UTC; 4min 1s ago
  Process: 706 ExecStart=/usr/libexec/registries -o /run/containers/registries.conf -V REGISTRIES (code=exited, status=1/FAILURE)
 Main PID: 706 (code=exited, status=1/FAILURE)
      CPU: 584ms

Sep 15 17:13:47 fedora26ah-dev registries[706]:     do_output(output, args)
Sep 15 17:13:47 fedora26ah-dev registries[706]:   File "/usr/lib/python3.6/site-packages/registries/registries.py", line 50, in do_output
Sep 15 17:13:47 fedora26ah-dev registries[706]:     write_file(args.output, output)
Sep 15 17:13:47 fedora26ah-dev registries[706]:   File "/usr/lib/python3.6/site-packages/registries/registries.py", line 34, in write_file
Sep 15 17:13:47 fedora26ah-dev registries[706]:     with open(filename,"w") as f:
Sep 15 17:13:47 fedora26ah-dev registries[706]: FileNotFoundError: [Errno 2] No such file or directory: '/run/containers/registries.conf'
Sep 15 17:13:47 fedora26ah-dev systemd[1]: registries.service: Main process exited, code=exited, status=1/FAILURE
Sep 15 17:13:47 fedora26ah-dev systemd[1]: Failed to start SystemWide Container Registries.
Sep 15 17:13:47 fedora26ah-dev systemd[1]: registries.service: Unit entered failed state.
Sep 15 17:13:47 fedora26ah-dev systemd[1]: registries.service: Failed with result 'exit-code'.

# journalctl -b -u registries
-- Logs begin at Thu 2017-08-31 14:16:30 UTC, end at Fri 2017-09-15 17:16:10 UTC. --
Sep 15 17:13:45 fedora26ah-dev systemd[1]: Starting SystemWide Container Registries...
Sep 15 17:13:47 fedora26ah-dev registries.log_warning[706]: /etc/containers/registries.conf is in YAML format and should be in TOML format. Back this file up and then use /usr/libexec/registries_migrator > /etc/
Sep 15 17:13:47 fedora26ah-dev registries[706]: Traceback (most recent call last):
Sep 15 17:13:47 fedora26ah-dev registries[706]:   File "/usr/libexec/registries", line 11, in <module>
Sep 15 17:13:47 fedora26ah-dev registries[706]:     load_entry_point('registries==0.1', 'console_scripts', 'registries')()
Sep 15 17:13:47 fedora26ah-dev registries[706]:   File "/usr/lib/python3.6/site-packages/registries/registries.py", line 146, in registries
Sep 15 17:13:47 fedora26ah-dev registries[706]:     do_output(output, args)
Sep 15 17:13:47 fedora26ah-dev registries[706]:   File "/usr/lib/python3.6/site-packages/registries/registries.py", line 50, in do_output
Sep 15 17:13:47 fedora26ah-dev registries[706]:     write_file(args.output, output)
Sep 15 17:13:47 fedora26ah-dev registries[706]:   File "/usr/lib/python3.6/site-packages/registries/registries.py", line 34, in write_file
Sep 15 17:13:47 fedora26ah-dev registries[706]:     with open(filename,"w") as f:
Sep 15 17:13:47 fedora26ah-dev registries[706]: FileNotFoundError: [Errno 2] No such file or directory: '/run/containers/registries.conf'
Sep 15 17:13:47 fedora26ah-dev systemd[1]: registries.service: Main process exited, code=exited, status=1/FAILURE
Sep 15 17:13:47 fedora26ah-dev systemd[1]: Failed to start SystemWide Container Registries.
Sep 15 17:13:47 fedora26ah-dev systemd[1]: registries.service: Unit entered failed state.
Sep 15 17:13:47 fedora26ah-dev systemd[1]: registries.service: Failed with result 'exit-code'.
```

This happened when the `atomic.spec` file changed here:

http://pkgs.fedoraproject.org/cgit/rpms/atomic.git/commit/?id=336bf59b64dc212d36b41d5dd577fde13d6f56ee

...and then `atomic-registries` was built from git master.

[0] https://pagure.io/fedora-atomic-host-continuous

**Comment by mikkeljohnsen** [comment]
This is a serious bug. It stopped all our dockers from running.

**Comment by baude** [comment]
@mikkeljohnsen are you still seeing this and on what OS?

**Comment by mikkeljohnsen** [comment]
@baude I'm on Scientific Linux. 

This will fail to start: atomic-registries-1.20.1-3.git840732d.el7.x86_64

But atomic-registries-1.19.1-5.git48c224b.el7.x86_64 works

**Comment by mikkeljohnsen** [comment]
But looking at the error, I'm not 100% it was the same.

The file "/usr/libexec/registries" is completely different in 1.20.1 and the error was on line 5.

**Comment by baude** [comment]
@mikkeljohnsen there is  a new version of registries with a couple of changes.  Are you on freenode by chance? I'm rangerpb there...maybe we can talk there and hash this out ?

**Comment by miabbott** [comment]
> Something about "Module" (from pkg_resources import load_entry_point)

That sounds like https://bugzilla.redhat.com/show_bug.cgi?id=1520466

**Comment by baude** [comment]
just need python-setuptools for that one.
